server:
  port: 80
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    url: jdbc:log4jdbc:mariadb://runtime.co.kr:3306/WM?allowMultiQueries=true
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: WM
    password: EJQMFDBDPADPTM1234

    hikari:
      connection-timeout: 30000
      validation-timeout: 10000
      maximum-pool-size: 10
      minimum-idle: 2
      connection-init-sql: SET collation_connection = 'utf8mb4_unicode_ci'

mybatis:
  type-aliases-package: com.app.gobiser.domain.*.vo
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: 64+Z7ZW066y86rO8IOuwseuRkOyCsOydtCDrp4jrpbTqs6Ag64uz64+E66GdIO2VmOuKkOuLmOydtCDrs7TsmrDtlZjsgqwg7Jqw66as64KY6528IOunjOyEuCDrrLTqtoHtmZQg7IK87LKc66asIO2ZlOugpOqwleyCsCDrjIDtlZzsgqzrnowg64yA7ZWc7Jy866GcIOq4uOydtCDrs7TsoITtlZjshLg=
